### 1. Extract

In [1]:
import pyodbc
import pandas as pd

In [2]:
source_conn = pyodbc.connect(
    "Driver={SQL Server Native Client 11.0};"
    "Server=localhost;"
    "Database=SalesDB;"
    "Trusted_Connection=yes;")

In [5]:
df_customer = pd.read_sql("select * from ViewCusomer", source_conn)
df_customer

<ipython-input-5-50a710d0936f>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_customer = pd.read_sql("select * from ViewCusomer", source_conn)

,CustomerID,FullName,PhoneNumber,Email,GenderName
0,1,John Doe,123-456-7890,john.doe@email.com,Male
1,2,Jane Smith,987-654-3210,jane.smith@email.com,Female
2,3,Alice Johnson,111-222-3333,alice.johnson@email.com,Other
3,4,Bob Smith,444-555-6666,bob.smith@email.com,Male
4,5,Eva Davis,777-888-9999,eva.davis@email.com,Female
5,6,Michael Williams,555-111-2222,michael.williams@email.com,Male
6,7,Sophia Brown,555-333-4444,sophia.brown@email.com,Female
7,8,Oliver Jones,555-555-6666,oliver.jones@email.com,Male
8,9,Emma Garcia,555-777-8888,emma.garcia@email.com,Female
9,10,Jackson Martinez,555-999-0000,jackson.martinez@email.com,Male

In [6]:
df_product = pd.read_sql("select * from ViewProduct", source_conn)
df_product

<ipython-input-6-c28b1c1ac3a9>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_product = pd.read_sql("select * from ViewProduct", source_conn)

,ProductID,ProductName,Price,SubCategoryName,CategoryName
0,1,"HL Road Frame - Black, 58",1431.50,Road Frames,Components
1,2,"HL Road Frame - Red, 58",1431.50,Road Frames,Components
2,3,"Sport-100 Helmet, Red",34.99,Helmets,Accessories
3,4,"Sport-100 Helmet, Black",34.99,Helmets,Accessories
4,5,"Mountain Bike Socks, M",9.50,Socks,Clothing
...,...,...,...,...,...
70,71,Water Bottle - 30 oz.,4.99,Bottles and Cages,Accessories
71,72,Patch Kit/8 Patches,2.29,Tires and Tubes,Accessories
72,73,Mountain Tire Tube,4.99,Tires and Tubes,Accessories
73,74,Road Tire Tube,3.99,Tires and Tubes,Accessories
74,75,Touring Tire Tube,4.99,Tires and Tubes,Accessories

In [7]:
df_salesman = pd.read_sql("select * from ViewSalesman", source_conn)
df_salesman

<ipython-input-7-d4f67a047b99>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_salesman = pd.read_sql("select * from ViewSalesman", source_conn)

,SalesmanID,FullName,Email,PhoneNumber,City
0,1,Mike Johnson,mike.johnson@email.com,555-123-4567,Cityville
1,2,Emily Taylor,emily.taylor@email.com,555-222-3333,Townsville
2,3,William Johnson,william.johnson@email.com,555-444-5555,Cityville
3,4,Ava Davis,ava.davis@email.com,555-666-7777,Villageton
4,5,Ethan Miller,ethan.miller@email.com,555-888-9999,Cityville
5,6,Sophie Anderson,sophie.anderson@email.com,555-000-1111,Townsville

In [8]:
df_FactOrders = pd.read_sql("select * from ViewFactOrders", source_conn)
df_FactOrders

<ipython-input-8-166f951ca8dd>:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_FactOrders = pd.read_sql("select * from ViewFactOrders", source_conn)

,OrderID,CustomerID,SalesmanID,OrderDate,ProductID,Quantity,TotalPrice
0,1,3,4,2023-01-01 10:00:00,22,3,1011.66
1,1,3,4,2023-01-01 10:00:00,15,5,7157.50
2,1,3,4,2023-01-01 10:00:00,1,6,8589.00
3,2,8,6,2023-01-01 11:30:00,7,4,139.96
4,2,8,6,2023-01-01 11:30:00,13,22,31493.00
5,3,3,6,2023-01-02 08:45:00,33,7,2360.54
6,4,3,6,2023-01-02 09:15:00,9,3,149.97
7,4,3,6,2023-01-02 09:15:00,10,5,249.95
8,5,5,4,2023-01-02 12:20:00,4,3,104.97
9,6,1,2,2023-02-07 11:30:00,45,2,7156.54
10,6,1,2,2023-02-07 11:30:00,12,5,249.95
11,6,1,2,2023-02-07 11:30:00,7,4,139.96
12,7,2,4,2023-02-07 13:45:00,34,1,337.22
13,8,8,3,2023-02-07 15:00:00,4,2,69.98
14,9,6,1,2023-03-03 13:10:00,39,3,4048.80
15,10,2,6,2023-04-08 11:25:00,52,6,8747.94
16,11,3,2,2023-04-08 12:00:00,70,5,16999.95
17,11,3,2,2023-04-08 12:00:00,57,8,6263.92
18,11,3,2,2023-04-08 12:00:00,63,2,1565.98
19,11,3,2,2023-04-08 12:00:00,43,1,1349.60

In [9]:
source_conn.close()

### 2. Transform

In [11]:
df_customer.head(5)

   CustomerID       FullName   PhoneNumber                    Email GenderName
0           1       John Doe  123-456-7890       john.doe@email.com       Male
1           2     Jane Smith  987-654-3210     jane.smith@email.com     Female
2           3  Alice Johnson  111-222-3333  alice.johnson@email.com      Other
3           4      Bob Smith  444-555-6666      bob.smith@email.com       Male
4           5      Eva Davis  777-888-9999      eva.davis@email.com     Female

In [12]:
df_customer.dtypes

CustomerID      int64
FullName       object
PhoneNumber    object
Email          object
GenderName     object
dtype: object

In [13]:
df_customer.isnull().sum()

CustomerID     0
FullName       0
PhoneNumber    0
Email          0
GenderName     0
dtype: int64

In [16]:
df_customer.value_counts()

CustomerID  FullName          PhoneNumber   Email                       GenderName
1           John Doe          123-456-7890  john.doe@email.com          Male          1
2           Jane Smith        987-654-3210  jane.smith@email.com        Female        1
3           Alice Johnson     111-222-3333  alice.johnson@email.com     Other         1
4           Bob Smith         444-555-6666  bob.smith@email.com         Male          1
5           Eva Davis         777-888-9999  eva.davis@email.com         Female        1
6           Michael Williams  555-111-2222  michael.williams@email.com  Male          1
7           Sophia Brown      555-333-4444  sophia.brown@email.com      Female        1
8           Oliver Jones      555-555-6666  oliver.jones@email.com      Male          1
9           Emma Garcia       555-777-8888  emma.garcia@email.com       Female        1
10          Jackson Martinez  555-999-0000  jackson.martinez@email.com  Male          1
Name: count, dtype: int64

In [18]:
df_product.head(5)

   ProductID                ProductName    Price SubCategoryName CategoryName
0          1  HL Road Frame - Black, 58  1431.50     Road Frames   Components
1          2    HL Road Frame - Red, 58  1431.50     Road Frames   Components
2          3      Sport-100 Helmet, Red    34.99         Helmets  Accessories
3          4    Sport-100 Helmet, Black    34.99         Helmets  Accessories
4          5     Mountain Bike Socks, M     9.50           Socks     Clothing

In [19]:
df_product.dtypes

ProductID            int64
ProductName         object
Price              float64
SubCategoryName     object
CategoryName        object
dtype: object

In [20]:
df_product.isnull().sum()

ProductID          0
ProductName        0
Price              0
SubCategoryName    0
CategoryName       0
dtype: int64

In [22]:
df_salesman.head(5)

,SalesmanID,FullName,Email,PhoneNumber,City
0,1,Mike Johnson,mike.johnson@email.com,555-123-4567,Cityville
1,2,Emily Taylor,emily.taylor@email.com,555-222-3333,Townsville
2,3,William Johnson,william.johnson@email.com,555-444-5555,Cityville
3,4,Ava Davis,ava.davis@email.com,555-666-7777,Villageton
4,5,Ethan Miller,ethan.miller@email.com,555-888-9999,Cityville

In [23]:
df_salesman.dtypes

SalesmanID      int64
FullName       object
Email          object
PhoneNumber    object
City           object
dtype: object

In [24]:
df_salesman.isnull().sum()

SalesmanID     0
FullName       0
Email          0
PhoneNumber    0
City           0
dtype: int64

In [25]:
df_FactOrders.head(5)

,OrderID,CustomerID,SalesmanID,OrderDate,ProductID,Quantity,TotalPrice
0,1,3,4,2023-01-01 10:00:00,22,3,1011.66
1,1,3,4,2023-01-01 10:00:00,15,5,7157.50
2,1,3,4,2023-01-01 10:00:00,1,6,8589.00
3,2,8,6,2023-01-01 11:30:00,7,4,139.96
4,2,8,6,2023-01-01 11:30:00,13,22,31493.00

In [31]:
df_FactOrders['OrderDate'] = pd.to_datetime(df_FactOrders['OrderDate'])

In [33]:
df_FactOrders['OrderDate'] = df_FactOrders['OrderDate'].dt.strftime('%Y%m%d')

In [35]:
df_FactOrders.dtypes

OrderID         int64
CustomerID      int64
SalesmanID      int64
OrderDate      object
ProductID       int64
Quantity        int64
TotalPrice    float64
dtype: object

In [ ]:
df_FactOrders['OrderDate'] = df_FactOrders['OrderDate'].astype(int)
df_FactOrders['Quantity'] = df_FactOrders['Quantity'].astype(float)

In [37]:
df_FactOrders.dtypes

OrderID         int64
CustomerID      int64
SalesmanID      int64
OrderDate       int32
ProductID       int64
Quantity      float64
TotalPrice    float64
dtype: object

### 3. Load

In [65]:
dwh_conn = pyodbc.connect(
    "Driver={SQL Server Native Client 11.0};"
    "Server=localhost;"
    "Database=SalesDWH;"
    "Trusted_Connection=yes;")

In [66]:
cusror = dwh_conn.cursor()

In [43]:
df_customer

,CustomerID,FullName,PhoneNumber,Email,GenderName
0,1,John Doe,123-456-7890,john.doe@email.com,Male
1,2,Jane Smith,987-654-3210,jane.smith@email.com,Female
2,3,Alice Johnson,111-222-3333,alice.johnson@email.com,Other
3,4,Bob Smith,444-555-6666,bob.smith@email.com,Male
4,5,Eva Davis,777-888-9999,eva.davis@email.com,Female
5,6,Michael Williams,555-111-2222,michael.williams@email.com,Male
6,7,Sophia Brown,555-333-4444,sophia.brown@email.com,Female
7,8,Oliver Jones,555-555-6666,oliver.jones@email.com,Male
8,9,Emma Garcia,555-777-8888,emma.garcia@email.com,Female
9,10,Jackson Martinez,555-999-0000,jackson.martinez@email.com,Male

In [49]:
for index, row in df_customer.iterrows():
    cusror.execute('insert into DimCustomer values (?,?,?,?,?)',row['CustomerID'],row['FullName'],row['PhoneNumber'],row['Email'],row['GenderName'])
dwh_conn.commit()

In [50]:
df_product

,ProductID,ProductName,Price,SubCategoryName,CategoryName
0,1,"HL Road Frame - Black, 58",1431.50,Road Frames,Components
1,2,"HL Road Frame - Red, 58",1431.50,Road Frames,Components
2,3,"Sport-100 Helmet, Red",34.99,Helmets,Accessories
3,4,"Sport-100 Helmet, Black",34.99,Helmets,Accessories
4,5,"Mountain Bike Socks, M",9.50,Socks,Clothing
...,...,...,...,...,...
70,71,Water Bottle - 30 oz.,4.99,Bottles and Cages,Accessories
71,72,Patch Kit/8 Patches,2.29,Tires and Tubes,Accessories
72,73,Mountain Tire Tube,4.99,Tires and Tubes,Accessories
73,74,Road Tire Tube,3.99,Tires and Tubes,Accessories
74,75,Touring Tire Tube,4.99,Tires and Tubes,Accessories

In [51]:
for index, row in df_product.iterrows():
    cusror.execute('insert into DimProduct values (?,?,?,?,?)',row['ProductID'],row['ProductName'],row['Price'],row['SubCategoryName'],row['CategoryName'])
dwh_conn.commit()

In [52]:
df_salesman

,SalesmanID,FullName,Email,PhoneNumber,City
0,1,Mike Johnson,mike.johnson@email.com,555-123-4567,Cityville
1,2,Emily Taylor,emily.taylor@email.com,555-222-3333,Townsville
2,3,William Johnson,william.johnson@email.com,555-444-5555,Cityville
3,4,Ava Davis,ava.davis@email.com,555-666-7777,Villageton
4,5,Ethan Miller,ethan.miller@email.com,555-888-9999,Cityville
5,6,Sophie Anderson,sophie.anderson@email.com,555-000-1111,Townsville

In [53]:
for index, row in df_salesman.iterrows():
    cusror.execute('insert into DimSalesman values (?,?,?,?,?)',row['SalesmanID'],row['FullName'],row['Email'],row['PhoneNumber'],row['City'])
dwh_conn.commit()

In [55]:
df_FactOrders.head(5)

   OrderID  CustomerID  SalesmanID  OrderDate  ProductID  Quantity  TotalPrice
0        1           3           4   20230101         22       3.0     1011.66
1        1           3           4   20230101         15       5.0     7157.50
2        1           3           4   20230101          1       6.0     8589.00
3        2           8           6   20230101          7       4.0      139.96
4        2           8           6   20230101         13      22.0    31493.00

In [67]:
for index, row in df_FactOrders.iterrows():
    cusror.execute('insert into FactOrders values (?,?,?,?,?,?,?)',row['OrderID'],row['CustomerID'],row['SalesmanID'],row['OrderDate'],row['ProductID'],row['Quantity'],row['TotalPrice'])
dwh_conn.commit()

In [68]:
dwh_conn.close()